language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pycodestyle
  - pip install codecov
  - pip install pytest-cov
# command to run tests
script:
  - pycodestyle --ignore=E501 main.py .
  - py.test -s --cov=./
after_success:
  - codecov
